import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'luxx-api-'));process.env.LUXX_LOCAL_STORAGE_DIR=path.join(root,'store');process.env.LUXX_LOCAL_AUTH_BYPASS='1';process.env.LUXX_PASSCODE='LUXX-TEST-PASSCODE';process.env.LUXX_SESSION_SECRET='test-session-secret-not-for-production-use-0123456789';process.env.LUXX_FFMPEG_PATH=process.env.LUXX_FFMPEG_PATH||'/usr/bin/ffmpeg';process.env.LUXX_FFPROBE_PATH=process.env.LUXX_FFPROBE_PATH||'/usr/bin/ffprobe';const FFMPEG=process.env.LUXX_FFMPEG_PATH;const {store}=await import('../netlify/lib/storage.mjs');const {STORES}=await import('../netlify/lib/model.mjs');
const names=['health','session','login','state','assets','upload-chunk','thumbnail','upload-complete','asset-update','asset-delete','image-edit','start-media-job','kick-media-job','process-media-job','process-media-job-background','renderer-health','job','variant-update','download-manifest','media-chunk','hls','action','settings','export-data','import-data','logout'];
const mods={};for(const n of names)mods[n]=(await import(`../netlify/functions/${n}.mjs`)).default;
const call=async(n,url='http://local/api/'+n,opt={})=>mods[n](new Request(url,{method:opt.method||'GET',headers:opt.headers||{},body:opt.body}));
const j=async r=>{const x=await r.json();return x};
const run=(bin,args)=>new Promise((resolve,reject)=>{const p=spawn(bin,args,{stdio:['ignore','ignore','pipe']});let e='';p.stderr.on('data',d=>e+=d);p.on('close',c=>c===0?resolve():reject(new Error(e.slice(-2000))));});
const passed=[];const ok=n=>passed.push(n);
let r=await call('health');assert.equal(r.status,200);assert((await j(r)).features.video_manual_edit);ok('health');
r=await call('session');assert.equal((await j(r)).authenticated,true);ok('session');
r=await call('login','http://local/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({passcode:'wrong'})});assert.equal(r.status,401);r=await call('login','http://local/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({passcode:process.env.LUXX_PASSCODE})});assert.equal(r.status,200);assert(r.headers.get('set-cookie')?.includes('luxx_session='));ok('login');
r=await call('state');assert.equal(r.status,200);ok('state');
r=await call('assets');assert.deepEqual((await j(r)).assets,[]);ok('assets');
// image chunk + thumbnail + complete
// The image fixture is generated into this run's temp dir. RC1 read it from an
// absolute machine path that does not ship with the package, so api-tests could
// never run anywhere but the box it was written on.
const imgPath=path.join(root,'test-image.png');await run(FFMPEG,['-y','-f','lavfi','-i','color=c=gray:s=240x320','-frames:v','1',imgPath]);
const img=await fs.readFile(imgPath);r=await call('upload-chunk','http://local/api/upload-chunk',{method:'POST',headers:{'x-luxx-asset-id':'IMG-API','x-luxx-part':'0','x-luxx-total-parts':'1'},body:img});assert.equal(r.status,200);ok('upload-chunk');
r=await call('thumbnail','http://local/api/thumbnail',{method:'POST',headers:{'x-luxx-asset-id':'IMG-API'},body:img});assert.equal(r.status,200);ok('thumbnail');
r=await call('upload-complete','http://local/api/upload-complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'IMG-API',name:'image.png',type:'image/png',size:img.length,parts:1,media_type:'IMAGE',authorization_status:'AUTHORIZED'})});assert.equal(r.status,200);const up=await j(r);assert.deepEqual(up.asset.platform_eligibility,['OnlyFans Free','OnlyFans Paid','Fansly']);assert.equal(up.asset.platform_eligibility_source,'LUXX_AUTO');ok('upload-complete');
// Simulate an asset saved by v1.3.0 before automatic destination planning existed, then verify GET /assets migrates it.
{const ast=await store(STORES.assets);const legacy=await ast.get('assets/IMG-API.json',{type:'json'});legacy.platform_eligibility=[];delete legacy.platform_eligibility_source;delete legacy.destination_plan;await ast.setJSON('assets/IMG-API.json',legacy);r=await call('assets');const migrated=(await j(r)).assets.find(x=>x.asset_id==='IMG-API');assert.deepEqual(migrated.platform_eligibility,['OnlyFans Free','OnlyFans Paid','Fansly']);assert.equal(migrated.platform_eligibility_source,'LUXX_AUTO');assert.equal(migrated.destination_plan.primary,'OnlyFans Free');}
r=await call('asset-update','http://local/api/asset-update',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'IMG-API',authorization_status:'AUTHORIZED',availability:'AVAILABLE',platform_eligibility:['X'],notes:'api updated'})});assert.equal((await j(r)).asset.notes,'api updated');ok('asset-update');
// settings: timezone is validated, stored, and unblocks the learned posting window
r=await call('settings','http://local/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({creatorTimezone:'Not/AReal Zone!!'})});assert.equal(r.status,400,'invalid timezone must be rejected');
r=await call('settings','http://local/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({creatorTimezone:'America/New_York'})});assert.equal(r.status,200);assert.equal((await j(r)).settings.creatorTimezone,'America/New_York');
r=await call('state');assert.equal((await j(r)).state.settings.creatorTimezone,'America/New_York');ok('settings');
r=await call('image-edit','http://local/api/image-edit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'IMG-API',auto_best:true})});const ie=await j(r);assert(ie.variant.rendered);ok('image-edit');
// safe unused duplicate deletion: store a disposable duplicate and verify asset + media removal.
{const ast=await store(STORES.assets),med=await store(STORES.media);const src=await ast.get('assets/IMG-API.json',{type:'json'});const dup={...src,asset_id:'IMG-DUP',name:'image duplicate.png',variants:[],use_count:0,ever_used_prospectively:false,uploaded_at:new Date().toISOString()};await ast.setJSON('assets/IMG-DUP.json',dup);await med.set('original/IMG-DUP/part-000000',img.buffer.slice(img.byteOffset,img.byteOffset+img.byteLength));r=await call('asset-delete','http://local/api/asset-delete',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'IMG-DUP'})});const dd=await j(r);assert.equal(r.status,200);assert.equal(dd.rule,'SAFE_UNUSED_DUPLICATE_ONLY');assert.equal(await ast.get('assets/IMG-DUP.json',{type:'json'}),null);assert.equal(await med.get('original/IMG-DUP/part-000000',{type:'arrayBuffer'}),null);ok('asset-delete');}
// tiny video for job/process/hls/download
const vf=path.join(root,'short.mp4');await run(FFMPEG,['-y','-f','lavfi','-i','testsrc2=size=160x90:rate=5','-t','8','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p',vf]);const vb=await fs.readFile(vf);r=await call('upload-chunk','http://local/api/upload-chunk',{method:'POST',headers:{'x-luxx-asset-id':'VID-API','x-luxx-part':'0','x-luxx-total-parts':'1'},body:vb});assert.equal(r.status,200);r=await call('upload-complete','http://local/api/upload-complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'VID-API',name:'short.mp4',type:'video/mp4',size:vb.length,parts:1,media_type:'VIDEO',authorization_status:'AUTHORIZED',platform_eligibility:['OnlyFans Paid']})});const vc=await j(r);assert(vc.asset.job_id);
r=await call('process-media-job','http://local/api/process-media-job',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:vc.asset.job_id})});assert.equal(r.status,410);ok('process-media-job');r=await call('process-media-job-background','http://local/api/process-media-job-background',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:vc.asset.job_id})});assert.equal(r.status,200);ok('process-media-job-background');r=await call('renderer-health');assert.equal(r.status,200);assert.equal((await j(r)).renderer,'READY');ok('renderer-health');r=await call('kick-media-job','http://local/api/kick-media-job',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:vc.asset.job_id})});assert.equal(r.status,200);ok('kick-media-job');
r=await call('job',`http://local/api/job?id=${encodeURIComponent(vc.asset.job_id)}`);assert.equal((await j(r)).job.status,'COMPLETE');ok('job');
r=await call('start-media-job','http://local/api/start-media-job',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'VID-API',kind:'VIDEO_EDIT',source_variant_id:'FULL-MASTER',recipe:{trim_start:0,trim_duration:3}})});const sj=await j(r);assert(sj.job.job_id);ok('start-media-job');
r=await call('process-media-job-background','http://local/api/process-media-job-background',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:sj.job.job_id})});assert.equal(r.status,200);
r=await call('assets');const va=(await j(r)).assets.find(x=>x.asset_id==='VID-API'),ev=va.variants.find(x=>x.parent_variant_id==='FULL-MASTER'||x.parent_variant_id==='MAIN-CUT');assert(ev);
r=await call('variant-update','http://local/api/variant-update',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:'VID-API',variant_id:'FULL-MASTER',platform:'OnlyFans Paid',final_runtime:va.variants.find(x=>x.variant_id==='FULL-MASTER').final_runtime,thumbnail_frame_timestamp_or_reference:'0.5s',title_direction:'Title',description_direction:'Description',cta:'Open the full paid drop.',tracking_route_id:'OF_PAID_PPV_01'})});assert.equal(r.status,200);ok('variant-update');
r=await call('download-manifest','http://local/api/download-manifest?asset=VID-API&variant=FULL-MASTER');const dm=await j(r);assert(dm.parts.length);ok('download-manifest');
r=await call('media-chunk','http://local'+dm.parts[0].url);assert.equal(r.status,200);assert((await r.arrayBuffer()).byteLength>0);ok('media-chunk');
r=await call('hls','http://local/api/hls?asset=VID-API&variant=FULL-MASTER');assert.equal(r.status,200);assert((await r.text()).includes('#EXTM3U'));ok('hls');
// action full path
r=await call('action','http://local/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'BASELINE_CAPTURE',payload:{evidence_reference:'api baseline',inventory_mapping_reference:'api inventory'}})});assert.equal(r.status,200);r=await call('action','http://local/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'BASELINE_LOCK',payload:{}})});assert.equal(r.status,200);r=await call('action','http://local/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'RECOMMEND',payload:{}})});assert.equal(r.status,200);ok('action');
r=await call('export-data','http://local/api/export-data?format=json');const exported=JSON.parse(await r.text());assert(exported.baseline.locked);ok('export-data');
r=await call('import-data','http://local/api/import-data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schemaVersion:'test',revenueEvents:[{revenue_event_id:'IMPORT-R1',action_id:null,event_type:'OTHER',gross_amount:1,attribution_precision:'UNATTRIBUTED'}]})});assert.equal(r.status,200);ok('import-data');
r=await call('logout');assert.equal(r.status,200);assert(r.headers.get('set-cookie').includes('Max-Age=0'));ok('logout');
const report={pass:passed.length===names.length,total:names.length,passed:passed.length,functions:passed,missing:names.filter(n=>!passed.includes(n))};await fs.writeFile('tests/API_TEST_RESULTS.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
