import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'luxx-e2e-'));
process.env.LUXX_LOCAL_STORAGE_DIR=path.join(root,'store');process.env.LUXX_LOCAL_AUTH_BYPASS='1';process.env.LUXX_FFMPEG_PATH='/usr/bin/ffmpeg';process.env.LUXX_FFPROBE_PATH='/usr/bin/ffprobe';
const run=(bin,args)=>new Promise((resolve,reject)=>{const p=spawn(bin,args,{stdio:['ignore','pipe','pipe']});let e='';p.stderr.on('data',d=>e+=d);p.on('close',c=>c===0?resolve():reject(new Error(e.slice(-2000))));});
const video=path.join(root,'seven-minute.mp4');
await run('/usr/bin/ffmpeg',['-y','-f','lavfi','-i','testsrc2=size=160x90:rate=5','-t','420','-c:v','libx264','-preset','ultrafast','-crf','38','-pix_fmt','yuv420p',video]);
const src=await fs.readFile(video);const originalHash=crypto.createHash('sha256').update(src).digest('hex');
const {CHUNK_SIZE,STORES}=await import('../netlify/lib/model.mjs');const upload=(await import('../netlify/functions/upload-chunk.mjs')).default;const {completeUpload}=await import('../netlify/functions/upload-complete.mjs');const {processVideoJob}=await import('../netlify/lib/video.mjs');const {store}=await import('../netlify/lib/storage.mjs');
const asset_id='VIDEO-E2E-001',parts=Math.ceil(src.length/CHUNK_SIZE);
for(let i=0;i<parts;i++){const b=src.subarray(i*CHUNK_SIZE,Math.min(src.length,(i+1)*CHUNK_SIZE));const req=new Request('http://local/api/upload-chunk',{method:'POST',headers:{'x-luxx-asset-id':asset_id,'x-luxx-part':String(i),'x-luxx-total-parts':String(parts),'content-type':'application/octet-stream'},body:b});const res=await upload(req);assert.equal(res.status,200);}
const complete=await completeUpload({asset_id,name:'seven-minute.mp4',type:'video/mp4',size:src.length,parts,media_type:'VIDEO'});assert(!complete.error);assert(complete.asset.job_id);
const result=await processVideoJob(complete.asset.job_id);assert.equal(result.job.status,'COMPLETE');assert.equal(result.asset.master_sha256,originalHash);assert.equal(Math.round(result.asset.analysis.duration_seconds),420);assert.equal(result.asset.analysis.plan.main.duration,300);assert.equal(result.asset.variants.length,4);assert(result.asset.variants.some(v=>v.variant_id==='MAIN-CUT'));assert.equal(result.asset.variants.filter(v=>v.variant_type==='TEASER').length,3);
const media=await store(STORES.media);for(const v of result.asset.variants){assert(v.download_parts.length>0);assert(v.hls_segments>0);assert(await media.get(`hls/${asset_id}/${v.variant_id}/index.m3u8`));}
// "Restart": make fresh store handles and re-read the persisted records/bytes from disk.
const assetsStore=await store(STORES.assets),jobsStore=await store(STORES.jobs);const persisted=await assetsStore.get(`assets/${asset_id}.json`,{type:'json'}),job=await jobsStore.get(`jobs/${complete.asset.job_id}.json`,{type:'json'});assert.equal(persisted.master_sha256,originalHash);assert.equal(persisted.variants.length,4);assert.equal(job.status,'COMPLETE');
const firstOriginal=await media.get(`original/${asset_id}/part-000000`,{type:'arrayBuffer'});assert(firstOriginal&&firstOriginal.byteLength>0);
const report={pass:true,asset_id,source_size:src.length,source_sha256:originalHash,parts,main_cut:persisted.variants.find(v=>v.variant_id==='MAIN-CUT'),teasers:persisted.variants.filter(v=>v.variant_type==='TEASER').map(v=>({id:v.variant_id,start:v.start_seconds,duration:v.duration_seconds,sha256:v.sha256,hls_segments:v.hls_segments,download_parts:v.download_parts.length})),restart_persistence:true};
await fs.writeFile(path.resolve('tests/E2E_RESULT.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
