import fs from 'node:fs/promises';import fss from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'luxx-media-tests-'));process.env.LUXX_LOCAL_STORAGE_DIR=path.join(root,'store');process.env.LUXX_LOCAL_AUTH_BYPASS='1';process.env.LUXX_FFMPEG_PATH=process.env.LUXX_FFMPEG_PATH||'/usr/bin/ffmpeg';process.env.LUXX_FFPROBE_PATH=process.env.LUXX_FFPROBE_PATH||'/usr/bin/ffprobe';
const {CHUNK_SIZE,STORES}=await import('../netlify/lib/model.mjs');const uploadFn=(await import('../netlify/functions/upload-chunk.mjs')).default;const {completeUpload}=await import('../netlify/functions/upload-complete.mjs');const {processVideoJob}=await import('../netlify/lib/video.mjs');const {editImage,editVideo}=await import('../netlify/lib/media-edit.mjs');const {store}=await import('../netlify/lib/storage.mjs');
const started=Date.now();
const stage=x=>console.log(`[MEDIA ${((Date.now()-started)/1000).toFixed(1)}s] ${x}`);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function uploadFile(fp,{asset_id,media_type,authorization_status='AUTHORIZED',platform_eligibility=[]}){const src=await fs.readFile(fp),parts=Math.ceil(src.length/CHUNK_SIZE);for(let i=0;i<parts;i++){const b=src.subarray(i*CHUNK_SIZE,Math.min(src.length,(i+1)*CHUNK_SIZE));const req=new Request('http://local/api/upload-chunk',{method:'POST',headers:{'x-luxx-asset-id':asset_id,'x-luxx-part':String(i),'x-luxx-total-parts':String(parts),'content-type':'application/octet-stream'},body:b});const res=await uploadFn(req);assert.equal(res.status,200,`upload chunk ${i}`);}const type=media_type==='VIDEO'?'video/mp4':'image/png';const r=await completeUpload({asset_id,name:path.basename(fp),type,size:src.length,parts,media_type,authorization_status,platform_eligibility});assert(!r.error,r.error);assert.equal(r.asset.master_sha256,sha(src));return {src,asset:r.asset};}
const report={pass:false,real_video:null,image:null,multichunk:null,elapsed_seconds:null};
try{
  stage('multichunk start');
  // Multi-chunk persistence with deterministic random bytes.
  const random=crypto.randomBytes(CHUNK_SIZE*2+321123),rf=path.join(root,'multi.bin');await fs.writeFile(rf,random);const up=await uploadFile(rf,{asset_id:'IMG-MULTI',media_type:'IMAGE'});const media=await store(STORES.media);let rebuilt=[];for(let i=0;i<up.asset.parts;i++)rebuilt.push(Buffer.from(await media.get(`original/IMG-MULTI/part-${String(i).padStart(6,'0')}`,{type:'arrayBuffer'})));const rb=Buffer.concat(rebuilt);assert.equal(sha(rb),sha(random));report.multichunk={bytes:random.length,parts:up.asset.parts,sha256:sha(random),restart_hash_match:true};
  stage('multichunk done; image start');
  // Image original + auto-best + edit-an-edit.
  // Fixture locations are configurable. LUXX_MEDIA_FIXTURE_IMAGE / LUXX_REAL_VIDEO let this
  // acceptance run point at whatever machine holds the real creator media.
  const img=process.env.LUXX_MEDIA_FIXTURE_IMAGE||'';assert(img&&fss.existsSync(img),`LUXX_MEDIA_FIXTURE_IMAGE is not set to an existing file: ${img||'(unset)'}`);const iu=await uploadFile(img,{asset_id:'IMG-EDIT-1',media_type:'IMAGE',platform_eligibility:['X']});const originalImageHash=iu.asset.master_sha256;const best=await editImage({asset_id:'IMG-EDIT-1',auto_best:true});assert.equal(best.variant.parent_variant_id,null);assert.equal(best.variant.rendered,true);assert.notEqual(best.variant.sha256,originalImageHash);const second=await editImage({asset_id:'IMG-EDIT-1',source_variant_id:best.variant.variant_id,recipe:{brightness:.01,contrast:1.02,saturation:1.01,warmth:0,sharpen:.2,aspect:'1:1'}});assert.equal(second.variant.parent_variant_id,best.variant.variant_id);const as=await store(STORES.assets);const persistedImg=await as.get('assets/IMG-EDIT-1.json',{type:'json'});assert.equal(persistedImg.master_sha256,originalImageHash);assert.equal(persistedImg.variants.length,2);report.image={master_sha256:originalImageHash,auto_best:best.variant.variant_id,second_generation:second.variant.variant_id,restart_master_hash_match:true};
  stage('image done; real video upload start');
  // Use the user's real uploaded the full probed duration master if available.
  const real=process.env.LUXX_REAL_VIDEO||'';assert(real&&fss.existsSync(real),`LUXX_REAL_VIDEO is not set to an existing file: ${real||'(unset)'}`);const vu=await uploadFile(real,{asset_id:'VIDEO-REAL-001',media_type:'VIDEO',platform_eligibility:['Pornhub','ManyVids','OnlyFans Paid']});const originalVideoHash=vu.asset.master_sha256;stage('real video uploaded; auto process start');const processed=await processVideoJob(vu.asset.job_id);stage('auto process done; edit rendered main start');assert.equal(processed.job.status,'COMPLETE');assert.equal(processed.asset.master_sha256,originalVideoHash);assert(processed.asset.analysis.duration_seconds>0,'the probed source duration must be preserved');const main=processed.asset.variants.find(v=>v.variant_id==='FULL-MASTER');const teasers=processed.asset.variants.filter(v=>v.variant_type==='TEASER');assert(main);assert(Math.abs(Number(main.duration_seconds)-Number(processed.asset.analysis.duration_seconds))<1.5,'the master must span the full source');assert.equal(teasers.length,3);for(const v of [main,...teasers]){assert(v.download_parts.length>0);assert(v.hls_segments>0);assert(await media.get(`hls/VIDEO-REAL-001/${v.variant_id}/index.m3u8`));}
  // Edit an already-rendered main cut into a new derivative.
  const ved=await editVideo({asset_id:'VIDEO-REAL-001',source_variant_id:'FULL-MASTER',recipe:{trim_start:2,trim_duration:12,brightness:.01,contrast:1.02,saturation:1.01,aspect:'ORIGINAL'}});assert.equal(ved.variant.parent_variant_id,'FULL-MASTER');assert.equal(Math.round(ved.variant.final_runtime),12);assert(ved.variant.download_parts.length>0);assert(ved.variant.hls_segments>0);
  stage('video edit done; persistence reread');
  const persistedVid=await as.get('assets/VIDEO-REAL-001.json',{type:'json'});assert.equal(persistedVid.master_sha256,originalVideoHash);assert(persistedVid.variants.some(v=>v.variant_id===ved.variant.variant_id));
  // Re-read storage handles after processing to simulate a new invocation/restart.
  const as2=await store(STORES.assets),media2=await store(STORES.media);const reread=await as2.get('assets/VIDEO-REAL-001.json',{type:'json'});assert.equal(reread.master_sha256,originalVideoHash);const first=Buffer.from(await media2.get('original/VIDEO-REAL-001/part-000000',{type:'arrayBuffer'}));assert(first.length>0);report.real_video={full_master:{duration_seconds:Number((processed.asset.variants.find(v=>v.variant_id==='FULL-MASTER')||{}).duration_seconds||0)},name:path.basename(real),bytes:vu.src.length,duration_seconds:processed.asset.analysis.duration_seconds,master_sha256:originalVideoHash,main_cut:{duration_seconds:main.duration_seconds,start_seconds:main.start_seconds,sha256:main.sha256,parts:main.download_parts.length,hls_segments:main.hls_segments},teasers:teasers.map(v=>({id:v.variant_id,start:v.start_seconds,duration:v.duration_seconds,sha256:v.sha256,parts:v.download_parts.length,hls_segments:v.hls_segments})),edited_derivative:{id:ved.variant.variant_id,parent:ved.variant.parent_variant_id,duration_seconds:ved.variant.final_runtime,sha256:ved.variant.sha256,parts:ved.variant.download_parts.length,hls_segments:ved.variant.hls_segments},restart_master_hash_match:true};
  stage('all media assertions done');
  report.pass=true;report.elapsed_seconds=Number(((Date.now()-started)/1000).toFixed(3));
}finally{await fs.writeFile('tests/MEDIA_TEST_RESULTS.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify(report,null,2));
